menu_items = [
    {
        "id": 1,
        "name": "Masala Chai",
        "category": "chai",
        "price": 30.0,
        "description": "Classic Indian spiced tea with ginger and cardamom",
        "available": True,
    },
    {
        "id": 2,
        "name": "Adrak Chai",
        "category": "chai",
        "price": 35.0,
        "description": "Extra ginger for cold evenings",
        "available": True,
    },
    {
        "id": 3,
        "name": "Elaichi Chai",
        "category": "chai",
        "price": 35.0,
        "description": "Aromatic chai flavored with cardamom",
        "available": True,
    },
    {
        "id": 4,
        "name": "Kesar Chai",
        "category": "chai",
        "price": 45.0,
        "description": "Rich chai infused with saffron",
        "available": True,
    },
    {
        "id": 5,
        "name": "Lemon Tea",
        "category": "tea",
        "price": 30.0,
        "description": "Refreshing tea with fresh lemon flavor",
        "available": True,
    },
    {
        "id": 6,
        "name": "Green Tea",
        "category": "tea",
        "price": 40.0,
        "description": "Light and refreshing green tea",
        "available": True,
    },
    {
        "id": 7,
        "name": "Cold Coffee",
        "category": "coffee",
        "price": 70.0,
        "description": "Chilled creamy coffee served cold",
        "available": True,
    },
    {
        "id": 8,
        "name": "Cappuccino",
        "category": "coffee",
        "price": 80.0,
        "description": "Hot coffee topped with steamed milk foam",
        "available": True,
    },
    {
        "id": 9,
        "name": "Veg Sandwich",
        "category": "snacks",
        "price": 60.0,
        "description": "Fresh vegetable sandwich with chutney and spices",
        "available": True,
    },
    {
        "id": 10,
        "name": "Samosa",
        "category": "snacks",
        "price": 20.0,
        "description": "Crispy Indian snack filled with spicy potatoes",
        "available": True,
    },
]
